#!/bin/sh

#
# File:         check_scribe 
# Description:  Nagios nrpe plugin for Scribe daemon
#
# History:
# Date		Author			Comment
# 2011-01-04    unbelievable machine    initial version 
# 2011-02-14    Josh Devins             added more states
#

# Nagios exit codes
nagios_ok=0
nagios_warning=1
nagios_critical=2
nagios_unknown=3

# Scribe service states mapped to Nagios codes
scribe_ok="ALIVE"
scribe_warning="WARNING"
scribe_critical="[(STARTING)(STOPPING)(STOPPED)(DEAD)(Failed to get status)]"

admin=/usr/sbin/scribe_ctrl

if [ ! -x $admin ]; then
        echo "UNKNOWN - Could not find the Scribe admin control command $admin"
        exit $nagios_unknown
fi

rval=`$admin status`

if [[ "$rval" =~ "$scribe_ok" ]]; then
        echo "OK"
        exit $nagios_ok

elif [[ "$rval" =~ "$scribe_warning" ]]; then
        echo "WARNING - $rval"

elif [[ "$rval" =~ "$scribe_critical" ]]; then
        echo "CRITICAL"
        exit $nagios_critical

else
        echo "UNKNOWN - Scribe dameon is in an unknown state: $rval"
        exit $nagios_unknown
fi

